### PR TITLE
Update Google Map JavaScript to use ES8, remove jQuery and be more modular.

### PR DESCRIPTION
**Pull request by adamjohnson**
Title pretty much explains this one.

Some things we might want to look into:

  * Currently not caching the JSON feed (via `crypto.randomUUID()`). Should we?
  * Should the `place.html` template be named something more descriptive? Perhaps `google_maps_place.html`?
  * Right now, we are putting the JS at the bottom of the DOM. If it was in its own file, it could be cached. What's the preference here? 

Let me know what you think.

### CODE REVIEW

**Comment by adamjohnson** [comment]
Oh, and you can see a demo of this on the [`google-map` branch on Volutus](https://designsystemv2demo.volutus.wvu.edu/google-map-test).

As of this writing, that branch is the currently selected branch in the theme properties.

**Comment by adamjohnson** [comment]
Also possibly relevant is the [`| to_json` filter](https://cleanslatecms.wvu.edu/how-to/theme-development/output-data-in-other-formats#liquid). 

Not sure if we'd want to use that in the [`map_data.json` template](https://github.com/wvuweb/wvu-design-system-v2/blob/master/views/map-data.json) or not.

I figure it's best to flesh out these details early, before anyone else uses this component in production.

**Comment by adamglenn** [comment]
@adamjohnson to answer some of your questions:

1. I don't know if you noticed, but I manually add a cache-buster link to the JSON feed when passing in the URL to the JS that builds out the map. I will do whatever is the best practice, but the reason I did this because during testing, it seemed like the page that has the map component and the JSON feed would get out of sync and it caused me to think something was busted. I could see this being frustrating to users. If we shouldn't do this, no big deal. I will just make note of it in the tutorial I'm creating.
2. The Place template is meant for any place/location, not necessarily for the map. So for example, if you wanted to feature a building/facility on your site, but don't have an actual map, you could use that template. The plan is to build that out a little more, maybe add regions for Hours of Operation or whatever else we think should be in this template. It's sort of like a Profile template, but for a place. This is something I had already considered when building the CAHS site, which wanted to feature their facilities.
3. Again, will do whatever is best practice, but the reason I included it in the component was to make it so someone could use the component without having to add a JS file to their theme. I know it's not hard to do that, so I'm good with whatever others think we should do.

Maybe @nreckart could weigh in?

**Comment by adamjohnson** [comment]
1. I will defer to @nreckart. 
2. Cool.
3. I moved this to its own file so that it is cached. If we're thinking about end users, going this route results in better performance and benefits the end user. Plus, we have other components that have external JS files.

I have "Synced Theme" on Volutus, so the demo link above should be ready to preview.

**Pull request merged**
