### PR TITLE
Transition from fonts.com to monotype.com for fonts. Fixes #7.

### LINKED ISSUE #7: Change from fonts.com to Monotype
Word on the street is that Monotype is the new font hosting service. They also serve their fonts from their CDN with `font-display: swap;` by default. So, we should be able to ditch FontFaceObserver.

If I don't get around to fixing/closing this issue, PM me about how to log into Monotype.

### PR DESCRIPTION
**Pull request by adamjohnson**
These changes work on the [demo site on Staging](https://designsystemv2demo.volutus.wvu.edu/) (make sure to select the correct branch). [Site Overview](https://cleanslate.volutus.wvu.edu/sites/1545) for that Staging site.

I have also implemented these same changes on [trails.wvu.edu](https://trails.wvu.edu)—which is in production.

I did introduce two new classes: `.helvetica-neue-italic` and `.helvetica-neue-bold-italic`. 

Monotype lets us automatically subset each font file to it's recommended settings (and, thus, the file is slightly smaller).

## Thoughts for the future

  * Individuals might consider self-hosting web fonts for better performance
    * The stylesheet linking to cdn.fonts.net is 1) an external resource and 2) uses `@import`.
    * As it is now, this external stylesheet is render blocking.
    * Users who want to self host their fonts should be sure to include the JS to report usage back to Monotype. Please note that it uses `eval()` and there might be security concerns there.
  * We might want to consider a loading strategy like [Zach did for CSS Tricks](https://www.zachleat.com/web/css-tricks-web-fonts/).
    * We are currently loading a LOT of web fonts. 🤷‍♂️
    * The [CSS Font Loading API](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Font_Loading_API) is probably helpful here.

cc/ @dmolsen

### CODE REVIEW

**Comment by dmolsen** [comment]
@adamjohnson -

Where did the tracking code come from? I went into Monotype and couldn't find a reference to it. They also don't have the big flashing warnings about limiting access to self-hosted fonts like fonts.com does. That makes me feel marginally better about self-hosting. 

If we don't go the self-host route, we **should not** let anyone else do it, either. My whole problem with self-hosting is not being on the hook for fonts getting ripped off.

> We are currently loading a LOT of web fonts. 

What's the list? I came up with a new loading scheme for `lite-yt-embed` so the JS/CSS only load if the element exists. I was considering something similar for FontAwesome (e.g. class exists, load FA). Not sure if it can be extended further.

**Comment by adamjohnson** [comment]
Funnily, if you click "Download Kit" once logged into Monotype, you will get the woff2 fonts but they don't include the tracking script. If you look at Monotype's [docs for self hosting](https://enterprise.monotype.com/help-center/font-management-collaboration/hosting-web-fonts-reporting), they reference `mtiFontTrackingCode.js`. I couldn't find this file anywhere on Monotype but fonts.com has this same file when you look to self host from fonts.com. We should probably contact Monotype about this.

You can see the fonts we use in [default.html](https://github.com/wvuweb/wvu-design-system-v2/pull/9/files#diff-4415eb83f07586acd531165e92b3cc7d66376d26f810d97730397fa3b5847dc2R17-R18) in this PR.

Optimizing delivery would probably include self hosting, initially only loading Helvetica Neue Bold Condensed and Helvetica Light, then using the CSS Font Loading API to load the rest of the fonts. Relevant article: [The best font loading strategies and how to execute them](https://css-tricks.com/the-best-font-loading-strategies-and-how-to-execute-them/) on CSS Tricks.

**Comment by adamjohnson** [comment]
> We should probably contact Monotype about this.

I just sent Monotype a support request about this. The automated message said they'd send me an email reply.

**Comment by dmolsen** [comment]
That's what I did (download) and was confused about the script ;) My Google fu was failing so thanks for finding the docs. Again, no dire warnings so I'd feel more comfortable with self-hosting. Thanks for following up with Monotype and we'll see what they say.

**Comment by adamjohnson** [comment]
After swapping a few emails with Monotype, I figured out how to properly self-host these web fonts. The key was in the `demo-async.htm` file in the download.

I will add a few commits to this PR that changes this implementation from using a CDN to self hosting. Will probably trial the commits in the [WVU Trails](https://trails.wvu.edu/) theme first.

**Comment by dmolsen** [comment]
Where are you thinking the self-hosted fonts are going to go?On Oct 3, 2022, at 3:57 PM, Adam Johnson ***@***.***> wrote:﻿
After swapping a few emails with Monotype, I figured out how to properly self-host these web fonts. The key was in the demo-async.htm file in the download.
I will add a few commits to this PR that changes this implementation from using a CDN to self hosting. Will probably trial the commits in the WVU Trails theme first.

**Comment by adamjohnson** [comment]
Each new theme will have a `~/public/fonts` directory. The fonts will live there.

Before you ask: putting them on static.wvu.edu (or any other wvu.edu domain) is not a good idea. If that were the case, we should just use their CDN.

**Comment by dmolsen** [comment]
I’m not dying on this hill. Just seems silly for milliseconds. On Oct 3, 2022, at 4:15 PM, Adam Johnson ***@***.***> wrote:﻿
Each new theme will have a ~/public/fonts directory. The fonts will live there.
Before you ask: putting them on static.wvu.edu (or any other wvu.edu domain) is not a good idea. If that were the case, we should just use their CDN.

**Pull request merged**
